substitutions:
  devicename: dew-point-example

esphome:
  name: ${devicename}
  friendly_name: ${devicename}

external_components: 
  - source:
      type: git
      url: https://github.com/floggy22/esphome_components
      ref: main    
    components: [ dew_point ]

esp32:
  board: esp32dev
  framework:  
    type: arduino

# Enable logging
logger:
  level: DEBUG

mqtt:
  broker: mybroker

ota:
  password: "mypassword"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
i2c:
  sda: 23
  scl: 22  
  id: 'bus_a'
  frequency: 400kHz

sensor:
  - platform: sht4x
    temperature:
      name: ${devicename} Temperature
      id: ta_sht4
    humidity:
      name: ${devicename} Relative Humidity
      id: ha_sht4
    update_interval: 60s  
  - platform: dew_point
    name: ${devicename} Dew Point Example
    temperature: ht_sht4
    humidity: ha_sht4
